name: dada2_learn_errors
description: |
  `DADA2 <https://benjjneb.github.io/dada2/index.html>`_
  Inferring sample composition using dada2 dada function.
authors:
  - Charlie Pauvert
input:
    derep: a RDS file withe the dereplicated sequences
    model: a RDS file with the error model
output:
  -  RDS file with the stored inferred sample composition
