name: dada2_learn_errors
description: |
  `DADA2 <https://benjjneb.github.io/dada2/index.html>`_
  Merging denoised forward and reverse reads using dada2 mergePairs function. Optional parameters are documented in the `manual <https://www.bioconductor.org/packages/release/bioc/manuals/dada2/man/dada2.pdf>`_.
authors:
  - Charlie Pauvert
input:
    dadaF: A RDS file with the inferred sample composition from forward reads 
    dadaR:                                                      reverse       
    derepF: A RDS file with the dereplicated forward reads
    derepR:                                  reverse      
params:
  - R optional arguments passed to the wrapped function as named Python arguments
output:
  - A RDS file with the merged pairs 
