name: dada2_quality_profiles
description: |
  `DADA2 <https://benjjneb.github.io/dada2/index.html>`_
  Plotting the quality profiles of paired-end reads using dada2 plotQualityProfile function.
authors:
  - Charlie Pauvert
input:
    fwd: a list of forward FASTQ files (potentially compressed)
    rev: a list of reverse FASTQ files (potentially compressed)
output:
    fwd: Plot of the random set of forward samples examined
    rev: Plot of the random set of reverse samples examined
params:
    n: the number of random samples to examine

