name: dada2_quality_profiles
description: |
  `DADA2 <https://benjjneb.github.io/dada2/index.html>`_
  Plotting the quality profiles of paired-end reads using dada2 plotQualityProfile function.
authors:
  - Charlie Pauvert
input:
    fwd: forward FASTQ file (potentially compressed) without primers sequences
    rev: reverse FASTQ file (potentially compressed) without primers sequences
output:
    plot: Path to the plot of forward and reverse reads examined
